### ISSUE TITLE
`no space left on device` during install

### ISSUE THREAD

**Issue by cfregly** [aws-samples/aws-mlflow-sagemaker-cdk#15]
```9c7d0e5c0bc2: Pull complete
failed to register layer: Error processing tar file(exit status 1): write /usr/share/doc/libgmpxx4ldbl/copyright: no space left on device
[100%] fail: docker build --tag cdkasset-71e655e29f8666a3fad012a03887e99b53a89027fc19f08de6c8cba71853bd8f . exited with error code 1: failed to register layer: Error processing tar file(exit status 1): write /usr/share/doc/libgmpxx4ldbl/copyright: no space left on device

 ❌  MLflowVpcStack failed: Error: Failed to publish one or more assets. See the error messages above for more information.
    at Object.publishAssets (/home/ec2-user/.nvm/versions/node/v16.14.0/lib/node_modules/aws-cdk/lib/util/asset-publishing.ts:25:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CloudFormationDeployments.publishStackAssets (/home/ec2-user/.nvm/versions/node/v16.14.0/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:424:7)
    at CloudFormationDeployments.deployStack (/home/ec2-user/.nvm/versions/node/v16.14.0/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:317:5)
    at CdkToolkit.deploy (/home/ec2-user/.nvm/versions/node/v16.14.0/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:201:24)
    at initCommandLine (/home/ec2-user/.nvm/versions/node/v16.14.0/lib/node_modules/aws-cdk/bin/cdk.ts:281:9)
Failed to publish one or more assets. See the error messages above for more information.
```

**Comment by cfregly** [comment]
increasing `resize-cloud9.sh` to use 100 (from 40)

**Comment by ibuchh** [comment]
Fixed !
